############################################################
#
# article-html微服务
# web访问端口号  约定：8002
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:123456@VMware:27017
      database: imooc-news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: VMware
    port: 5672
    username: jgl
    password: 123456
    virtual-host: imooc-news

# 定义freemarker生成的html位置
freemarker:
  html:
    article: D:\Tomcat\apache-tomcat-8.5.75\webapps\imooc-news\portal\a